import { Inter } from "next/font/google";
import Head from "next/head";
import MenuCpn from "src/components/MenuCpn";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container-tcd">
        <h1>Trang chủ</h1>
        <MenuCpn></MenuCpn>
      </div>
    </>
  );
}
